### ISSUE TITLE
app Suggestion: netbox

### ISSUE THREAD

**Issue by woodsb02** [truenas/apps#1005]
NetBox exists to empower network engineers. Since its release in 2016, it has become the go-to solution for modeling and documenting network infrastructure for thousands of organizations worldwide. As a successor to legacy IPAM and DCIM applications, NetBox provides a cohesive, extensive, and accessible data model for all things networked. By providing a single robust user interface and programmable APIs for everything from cable maps to device configurations, NetBox serves as the central source of truth for the modern network.

https://netboxlabs.com/oss/netbox/
https://github.com/netbox-community/netbox-docker

**Comment by teunbruijnen** [comment]
I'm currently running it as a custom app but still haven't been able to make it work with plugins yet. 

Would be great to have netbox as an official app with possibility to install plugins.

My yaml file:

```yaml
services:
  netbox:
    depends_on:
      - postgres
      - redis
      - redis-cache
    env_file: /mnt/BigPool/Apps/netbox/netbox-docker/env/netbox.env
    healthcheck:
      interval: 15s
      start_period: 90s
      test: curl -f http://localhost:8080/login/ || exit 1
      timeout: 3s
    image: docker.io/netboxcommunity/netbox:latest
    ports:
      - '10888:8080'
    user: unit:root
    volumes:
      - /mnt/BigPool/Apps/netbox/netbox-docker/configuration:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
  netbox-housekeeping:
    command:
      - /opt/netbox/housekeeping.sh
    depends_on:
      netbox:
        condition: service_healthy
    env_file: /mnt/BigPool/Apps/netbox/netbox-docker/env/netbox.env
    healthcheck:
      interval: 15s
      start_period: 20s
      test: ps -aux | grep -v grep | grep -q housekeeping || exit 1
      timeout: 3s
    image: docker.io/netboxcommunity/netbox:latest
    user: unit:root
    volumes:
      - /mnt/BigPool/Apps/netbox/netbox-docker/configuration:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
  netbox-worker:
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    depends_on:
      netbox:
        condition: service_healthy
    env_file: /mnt/BigPool/Apps/netbox/netbox-docker/env/netbox.env
    healthcheck:
      interval: 15s
      start_period: 20s
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      timeout: 3s
    image: docker.io/netboxcommunity/netbox:latest
    user: unit:root
    volumes:
      - /mnt/BigPool/Apps/netbox/netbox-docker/configuration:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
  postgres:
    env_file: /mnt/BigPool/Apps/netbox/netbox-docker/env/postgres.env
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 20s
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 30s
    image: docker.io/postgres:17-alpine
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
  redis:
    command:
      - sh
      - '-c'
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD
    env_file: /mnt/BigPool/Apps/netbox/netbox-docker/env/redis.env
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 5s
      test: '[ $$(valkey-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      timeout: 3s
    image: docker.io/valkey/valkey:8.0-alpine
    volumes:
      - netbox-redis-data:/data
  redis-cache:
    command:
      - sh
      - '-c'
      - valkey-server --requirepass $$REDIS_PASSWORD
    env_file: /mnt/BigPool/Apps/netbox/netbox-docker/env/redis-cache.env
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 5s
      test: '[ $$(valkey-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      timeout: 3s
    image: docker.io/valkey/valkey:8.0-alpine
    volumes:
      - netbox-redis-cache-data:/data
volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-reports-files:
    driver: local
  netbox-scripts-files:
    driver: local

```
