### ISSUE TITLE
build args not being passed to dockerfile_inline

### ISSUE THREAD

**Issue by Always-Self-Hosted** [truenas/apps#1344]
If you try to use dockerfile_inline with the custom yaml option of the truenas apps (tested on scale electric eel 24.10.1) the build args are not being passed in and the build fails. For the full context i posted it on the help forum here (https://forums.truenas.com/t/truenas-scale-electric-eel-docker-compose-with-dockerfile-inline/30561) but below i will truncate what i believe to be the important parts

```
proton-bridge:
    build:
      args:
        - PROTON_BRIDGE_VERSION=3.16.0
      dockerfile_inline: |
        FROM golang:1.21.9 as build
        ARG PROTON_BRIDGE_VERSION
        RUN git clone https://github.com/ProtonMail/proton-bridge.git
        WORKDIR proton-bridge
        RUN git checkout tags/v$PROTON_BRIDGE_VERSION
        CMD echo $PROTON_BRIDGE_VERSION
      tags:
        - inline-proton-bridge:custom
```

```
[2025/01/11 13:53:47] (ERROR) app_lifecycle.compose_action():56 - Failed 'up' action for 'onedev' app:
time="2025-01-11T13:53:41+10:00" level=warning msg="The \"PROTON_BRIDGE_VERSION\" variable is not set. Defaulting to a blank string."
failed to solve: process "/bin/sh -c git checkout tags/v" did not complete successfully: exit code: 1
```

I have done what i can on my end to make sure this is the problem by obviously getting this in a working state locally via `docker build --build-arg PROTON_BRIDGE_VERSION=3.16.0 --tag inline-proton-bridge:custom --file Dockerfile .` and `docker run --rm -it inline-proton-bridge:custom` and also by confirming if i remove the args block from my custom docker compose yaml and just hardcode the value inside the dockerfile_inline block then truenas apps actually builds and deploys it all as expected.

**Comment by stavros-k** [comment]
Hello, please see https://stackoverflow.com/questions/40619582/how-can-i-escape-a-dollar-sign-in-a-docker-compose-file

**Comment by stavros-k** [comment]
And https://docs.docker.com/reference/compose-file/interpolation/

Closing as it works as intended

**Comment by stavros-k** [comment]
Yes I'm sure, you still not escaping `$`

```sh
$${PROTON_BRIDGE_VERSION}
```

**Comment by Always-Self-Hosted** [comment]
```
proton-bridge:
    build:
      args:
        - PROTON_BRIDGE_VERSION=3.16.0
      dockerfile_inline: |
        FROM golang:1.21.9 as build
        ARG PROTON_BRIDGE_VERSION
        RUN git clone https://github.com/ProtonMail/proton-bridge.git
        WORKDIR proton-bridge
        RUN git checkout tags/v$${PROTON_BRIDGE_VERSION}
        CMD echo $${PROTON_BRIDGE_VERSION}
      tags:
        - inline-proton-bridge:custom
```
```
[2025/01/13 23:46:46] (ERROR) app_lifecycle.compose_action():56 - Failed 'up' action for 'proton-bridge' app:  proton-bridge Pulling 
 proton-bridge Warning pull access denied for proton-bridge, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
failed to solve: process "/bin/sh -c git checkout tags/v${PROTON_BRIDGE_VERSION}" did not complete successfully: exit code: 1
```

:disappointed:

**Comment by stavros-k** [comment]
This works fine for me
```yaml
services:
  proton-bridge:
    build:
      args:
        - PROTON_BRIDGE_VERSION=3.15.0
      dockerfile_inline: |
        FROM golang:1.21.9 AS build
        ARG PROTON_BRIDGE_VERSION
        RUN git clone https://github.com/ProtonMail/proton-bridge.git
        WORKDIR proton-bridge
        RUN git checkout tags/v$${PROTON_BRIDGE_VERSION}
        RUN echo $${PROTON_BRIDGE_VERSION} > /file.txt
        CMD echo $${PROTON_BRIDGE_VERSION}
      tags:
        - inline-proton-bridge:15
    entrypoint: |
      /bin/bash -c 'cat /file.txt && sleep infinity'
```
