### ISSUE TITLE
Steam-Headless not working correctly when there is no display

### ISSUE THREAD

**Issue by Tenster** [truenas/apps#1424]
Hello,

it's great to see that we now have Steam Headless directly included in the packs. However, the port currently lacks proper functionality and configuration options.

Here are some configuration options I think that would be very useful to include:

```bash
 MODE=primary
 WEB_UI_MODE=vnc
 ENABLE_VNC_AUDIO=true
 ENABLE_STEAM=true
 STEAM_ARGS=silent
 ENABLE_SUNSHINE=false
 SUNSHINE_USER=USER
 SUNSHINE_PASS=PASSWORD
 ENABLE_EVDEV_INPUTS=true
 FORCE_X11_DUMMY_CONFIG=true
 NVIDIA_DRIVER_CAPABILITIES=all
 NVIDIA_VISIBLE_DEVICES=all
 NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION}
```
The most critical point here is the FORCE_X11_DUMMY_CONFIG setting. Without this, the service doesn't start on my setup because no display is connected.

Additionally, there seems to be an issue with accessing nvidia-smi as it throws an error that it cannot be found, probably because you are not able to select the GPU.

Below is my working configuration for reference:

```yaml
services:
  steam-headless:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - '0000:02:00.0'
    device_cgroup_rules:
      - c 13:* rmw
    devices:
      - /dev/fuse
      - /dev/uinput
    environment:
      - TZ=CET
      - USER_LOCALES=en_US.UTF-8
      - DISPLAY=:55
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - USER_PASSWORD=${USER_PASSWORD}
      - MODE=primary
      - WEB_UI_MODE=vnc
      - ENABLE_VNC_AUDIO=true
      - PORT_NOVNC_WEB=8083
      - NEKO_NAT1TO1=${NEKO_NAT1TO1}
      - ENABLE_STEAM=true
      - STEAM_ARGS=silent
      - ENABLE_SUNSHINE=true
      - SUNSHINE_USER=toro
      - SUNSHINE_PASS=s41a23l51*
      - ENABLE_EVDEV_INPUTS=true
      - FORCE_X11_DUMMY_CONFIG=true
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION}
    extra_hosts:
      - system name:127.0.0.1
    hostname: HOST
    image: josh5/steam-headless:latest
    ipc: host
    network_mode: host
    privileged: True
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    shm_size: 2048
    ulimits:
      nofile:
        hard: 524288
        soft: 1024
    volumes:
```
