### ISSUE TITLE
Request: Kiwix Server

### ISSUE THREAD

**Issue by Shrinks99** [truenas/apps#1427]
[Kiwix](https://github.com/kiwix/kiwix-tools) allows users to serve an offline copy of Wikipedia!  [Docker packages are available](https://github.com/orgs/kiwix/packages).

**Comment by highb** [comment]
I have attempted to configure Kiwix using the same parameters as the old TrueCharts config but it won't even launch the container for long enough that I can read any logs so I'm a bit stumped as to what steps to take next on it. https://github.com/trueforge-org/truecharts/blob/master/charts/stable/kiwix-serve/values.yaml

I ended up running Portainer and using this docker-compose. It worked fine.
```yaml

services:
  kiwix-serve:
      ports:
        - 40001:8080
      image: ghcr.io/kiwix/kiwix-serve:3.7.0
      command: 
        - '*.zim'
      volumes: ["/mnt/tank/mirrors/kiwix:/data"]
```
