### ISSUE TITLE
Collabora extra_params not applied correctly

### ISSUE THREAD

**Issue by herrlegno** [truenas/apps#1578]
I'm trying to apply `--o:ssl.enable=false`, but it doesn't work, something is overwriting this value.

Expected Behaviour:
Apply the value I'm setting, in this case `false`

![Image](https://github.com/user-attachments/assets/dbcc2952-94e2-4154-a315-be3a8e468ca3)

Actual Behaviour:
Ignores this setting and applies `true`

![Image](https://github.com/user-attachments/assets/5da1cb0e-ee19-4cbc-af21-d13fa1e1825c)

Version:
Collabora App:
![Image](https://github.com/user-attachments/assets/7687a729-56e1-493a-a95c-81a0cfb745d6)

TrueNAS  Scale: ElectricEel-24.10.2

**Comment by stavros-k** [comment]
Hello, please see this
https://github.com/CollaboraOnline/online/issues/894#issuecomment-750330201

This is expected behavior

**Comment by herrlegno** [comment]
@stavros-k I can make it work using a docker-compose file simple as, seems something with the `truenas` config:
```yml
services:
  collabora:
    image: collabora/code
    container_name: collabora
    ports:
        - "9980:9980"
    restart: unless-stopped
    environment:
        - extra_params=--o:ssl.enable=false
        - domain=192.168.1.140
        - username=whatever
        - password=whatever
```
