### ISSUE TITLE
request: Stirling PDF

### ISSUE THREAD

**Issue by TDuffinNTU** [truenas/apps#1658]
StirlingPDF is a self-hosted PDF manipulation suite.

[Website](https://www.stirlingpdf.com/about)
[DockerHub](https://hub.docker.com/r/stirlingtools/stirling-pdf)

Docker Compose example
```
version: '3.3'
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - /path/to/training/data:/usr/share/tessdata #Required for extra OCR languages
      - /path/to/configs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
```

This should be a very easy one to set up. It requires no special permissions, and the two listed volumes appear to work fine within the same directory. I have mine set to a single dataset with the group/user `apps` given rw permissions.

The dockerhub has a list of other configs that could be added too.
