### ISSUE TITLE
gitea-act-runner fails to set up job

### ISSUE THREAD

**Issue by luisjira** [truenas/apps#1692]
I installed the gitea-act-runner app and verified that it successfully registered with the gitea app on the same machine.
When testing a small Gitea Action the runner failed to set up the job with this error:
`Unable to clone https://github.com/actions/checkout refs/heads/v2: mkdir /.cache: permission denied`

The Gitea Action:
```
name: Checkout

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
```

Additionally, the docker logs show this immediately after startup:
`[...] level=error msg="cannot init cache server, it will be disabled: mkdir /.cache: permission denied"`

For personal use, I don't mind having the cache server disabled, but actions should run without problems.

To fix both errors, I added the environment variable `HOME` with value `/data`. Now the checkout action is cloned to `/data/.cache/...` and completes successfully.

Note: `/data` is the default "Gitea Act Runner Data Storage" configured for the app. Thus, I believe adding this variable to the default setup would be a good option.
