### ISSUE TITLE
App Request: SwarmUI / ComfyUI / AI image generation

### ISSUE THREAD

**Issue by maas-gross** [truenas/apps#1728]
# Why it is useful?
After getting Ollama and OpenWebUI, image generation is still missing from the catalogue. This makes OpenWebUI only half-baked compared to OpenAI.

OpenWebUI could be a proper self-hosted private OpenAI replacement if we had an image generation app. This technology is gaining more importance and should be accessible to everyone.

Content creators can leverage their TrueNAS not only for storage, but also for content creation like script improvements or thumbnail generation.
Having a full AI suite could be a selling factor for a TrueNAS system for a business.
Homelab people can educate themselves and their surroundings into using AI in a local and therefore private way.

# What is it?
SwarmUI is a UI for stable diffusion image generation. SwarmUI sits ot top of ComfyUI, which is the most advanced open-source Stable Diffusion backend to my knowledge. In contrast to other implementations, SwarmUI exposes all of ComfyUI's functionality.

# Resources
SwarmUI on Github: https://github.com/mcmonkeyprojects/SwarmUI
Docker-Compose: https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docker-compose.yml

**Comment by maas-gross** [comment]
I wanted to add that I got ComfyUI working as a custom app. In case someone wants to get it working too:
I used this Repo as a reference:
https://github.com/YanWenKun/ComfyUI-Docker
Here is my modified compose.yaml:
~~~yaml
services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - '0'
              driver: nvidia
    environment:
      - CLI_ARGS=
    image: yanwk/comfyui-boot:cu124-slim
    init: True
    ports:
      - '8188:8188'
    security_opt:
      - label=type:nvidia_container_t
    volumes:
      - /mnt/poolname/path/to/comfyui/data:/root # needs to be there, dont know why
      - /mnt/poolname/path/to/comfyui/input:/root/ComfyUI/input
      - /mntpoolname/path/to/comfyui/output:/root/ComfyUI/output
      - /mnt/poolname/path/to/comfyui/models:/root/ComfyUI/models
~~~
Issues are: Comfy grabs a lot of memory and holds on to it untill you stop the container. For me ~ 20GB

**Comment by lawful123** [comment]
Did not work. using electric eel. would install but, would not start. I used this.

```yaml
version: '3.8'
services:
  comfyui:
    image: yanwk/comfyui-boot:cu124-slim
    container_name: comfyui
    environment:
      - CLI_ARGS=
    ports:
      - '8188:8188'
  volumes:
      - /mnt/poolname/path/to/comfyui/data:/root # needs to be there, dont know why
      - /mnt/poolname/path/to/comfyui/input:/root/ComfyUI/input
      - /mntpoolname/path/to/comfyui/output:/root/ComfyUI/output
      - /mnt/poolname/path/to/comfyui/models:/root/ComfyUI/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - '0'
              driver: nvidia
    security_opt:
      - label=type:nvidia_container_t
    init: true
    network_mode: host
```
