### ISSUE TITLE
open-webui Pipelines not working due to missing internal endpoint

### ISSUE THREAD

**Issue by hugalafutro** [truenas/apps#1784]
open-webui expects `http://host.docker.internal:9099` (that is not alliteration it expects that literal string as host) exposed as oai endpoint internally with api key of `0p3n-w3bu!` for the Pipelines functionality (more at https://github.com/open-webui/open-webui/discussions/3206), it comes from this in their docker-compose.yml:
```
  open-webui:
...
    extra_hosts:
      - host.docker.internal:host-gateway
...
```
or this from docker command argument `--add-host=host.docker.internal:host-gateway`

However it does not work when open-webui runs as Scale app.
![Image](https://github.com/user-attachments/assets/801b35e1-80af-4cd5-a4ea-1e9de7dbd358)
![Image](https://github.com/user-attachments/assets/4b0b9cd5-ce04-4522-9821-a97d31ba32b0)

It works as expected without the extra configuration running with docker-compose on different host.

**Comment by hugalafutro** [comment]
Hi was this merged already in v1.0.40? I updated the app today, but the Pipelines still do not work either out-of-the-box or with adding the address manually. Output is same as screenshots above. 

Pipelines is needed for function calls, amongst other things it's the only way to connect open-webui with Anthropic API

**Comment by stavros-k** [comment]
Yes it should be there.
You can try resolving the `host.docker.internal` within the container to see if it resolves correctly.

But re-reading the issue linked, the extra host is not really needed.
Well its needed under specific scenarios.

What's the actual requirement here, is the `pipelines` container to be running, which is a **separate** one.

**Comment by stavros-k** [comment]
Re-opening as enhancement to add that extra container.

**Comment by hugalafutro** [comment]
I read about the extra container and running the open-webui in docker didn't require additional container. I migrated from docker install to Scale and the pipelines stopped working which is how I discovered about the extra address.

So it confuses me why would it need extra container suddenly.

Thank you for your work on fixing the issue!

**Comment by stavros-k** [comment]
I've no idea how you where running it before. But that's from their docs

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/80e7eebc-25d4-443d-ade6-a943b89b07f9" />

**Comment by hugalafutro** [comment]
This is docker-compose I ran it with in vm, pipelines were working as Claude was last model I used
```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    container_name: open-webui
    volumes:
      - ./data:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OAIAPI}
      - AUTOMATIC1111_BASE_URL=${A1111URL}
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_MODEL=perfectdeliberate_v5
      - IMAGE_SIZE=512x512
    ports:
      - 3333:8080
networks: {}
```

the address seems to exist in the container, but it doesn;t function as OAI endpoint
```
root@truenas[/home/admin]# docker exec ix-open-webui-open-webui-1 bash -c "curl host.docker.internal"        
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0   123k      0 --:--:-- --:--:-- --:--:--  134k
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I'm too inexperienced to check for the port, but trying to ad it into the app as in original post results in same error message.

I'm not trying to be confrontational, just genuinely wondering as the above docker-compose everything worked and in scale it doesn't.
