### ISSUE TITLE
Community App Suggestion: mitmproxy [app-request]

### ISSUE THREAD

**Issue by jondycz** [truenas/apps#1814]
I'd like to suggest an app called mitmproxy, functioning basically like a chrome dev tools for all proxied devices. Great for debugging devices like phones where developer tool use is limited.

Dockerhub: https://hub.docker.com/r/mitmproxy/mitmproxy/

My working docker compose / custom app yaml config from TrueNAS.

```
services:
  mitmproxy:
    command: mitmweb --web-host 0.0.0.0
    image: mitmproxy/mitmproxy
    ports:
      - '8088:8080'
      - '8089:8081'
    restart: unless-stopped
    stdin_open: True
    tty: True
```

Though the config is missing a persistent volume for the certificate store.
