### ISSUE TITLE
Community app contribution: monitee-agent

### ISSUE THREAD

**Issue by Krillsson** [truenas/apps#1869]
I'm the author of [Monitee](https://monitee.app/), a server monitoring solution with an android app as the main interaction point. I am aiming to contribute a community app for the [agent](https://github.com/Krillsson/monitee-agent) component.

I'm pasting my latest sample docker-compose.yml below. Feel free to give me heads up around any gotchas you see with it in relation to your solution or if you have any pointers.

```yaml
version: "3"
services:
  sys-api:
    container_name: monitee-agent
    # krillsson/sys-api:native to try the native build
    image: krillsson/sys-api:latest
    # exposes NIC's for sys-API to read
    network_mode: host
    cap_add:
     # read SMART data 
      - SYS_RAWIO
    # Uncomment if you don't want to run in network_mode: host
    # ports:
    # - "8080:8080"
    # - "8443:8443"
    #  # port for docker management API.
    # - "2375:2375"
    # expose host processes for container.
    pid: "host"
    volumes:
      # change "/path/to/*" point to a directory on your machine
      - /path/to/data:/data
      - /path/to/config:/config
      # socket for docker management API.
      - /var/run/docker.sock:/var/run/docker.sock
      # to read device names from disks
      - /run/udev:/run/udev:ro
      # to control systemd
      - /run/systemd:/run/systemd
      # to read journal logs
      - /etc/machine-id:/etc/machine-id:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro
      - /run/log/journal:/run/log/journal:ro
      # to allow sys-API access to read info about disks
      - /dev:/dev:ro
      # same as above
      - /srv:/srv:ro
      # show correct os info in about server screen
      - /etc/os-release:/etc/os-release
    # temperature monitoring of disks
    #devices:
    #  - "/dev/sda:/dev/sda"
    restart: unless-stopped
```
