### ISSUE TITLE
Community Chart Suggestion: GitLab

### ISSUE THREAD

**Issue by Plinsboorg** [truenas/apps#201]
https://about.gitlab.com/install/

**Comment by fuzzybair** [comment]
I was going to submit a ticket for this as well. I found this pull request by @hartzell 
 https://github.com/truenas/apps/pull/1252/commits I was wondering if there was anything I could do to help with it?

**Comment by fuzzybair** [comment]
@stavros-k I was looking at picking this up however I have a concern on managing upgrades. Is it possible to limit users from upgrading if they are not on a minimum version?

For example to upgrade Gitlab 17.1.8 to 17.5.5 you must first upgrade to 17.3.7. see https://docs.gitlab.com/update/upgrade_paths/ While it is possible to keep all the versions as they come up to date, It is also entirely possible that busy individuals will not have time to keep their NAS up to date and may attempt to just jump to the latest version and cause themselves lost data.

**Comment by hartzell** [comment]
FWIW, I don't have the time to work further on this.

**Comment by stavros-k** [comment]
> [@stavros-k](https://github.com/stavros-k) I was looking at picking this up however I have a concern on managing upgrades. Is it possible to limit users from upgrading if they are not on a minimum version?
> 
> For example to upgrade Gitlab 17.1.8 to 17.5.5 you must first upgrade to 17.3.7. see https://docs.gitlab.com/update/upgrade_paths/ While it is possible to keep all the versions as they come up to date, It is also entirely possible that busy individuals will not have time to keep their NAS up to date and may attempt to just jump to the latest version and cause themselves lost data.


From 25.04 there will be 2 ways to deal with this. Now there is 1.

- Using jinja inside the docker-compose.yaml template you can access the app metadata and fail to render the template if you detect that you shouldnt.
- From 25.04, there will be schema migration functionality (see #1550 for example). So you can do python code and check if its within the versions and either fail the migration (failing the upgrade as well) or return the schema as is.

But tbh, that will get real complex real fast.
- Ideally, gitlab should fail to even start if it detects incompatible previous version, so users can safely go back and upgrade step by step.
- In our case, we can keep it "simple" and just **keep** the "milestone" versions available. And users should upgrade one version at a time. Well in that case, if we keep specific versions available, we can do basic checks directly in the jinja.

**Comment by fuzzybair** [comment]
> - Ideally, gitlab should fail to even start if it detects incompatible previous version, so users can safely go back and upgrade step by step.
> - In our case, we can keep it "simple" and just keep the "milestone" versions available. And users should upgrade one version at a time. Well in that case, if we keep specific versions available, we can do basic checks directly in the jinja.

I agree gitlab really should protect the upgrade better, but that is out of my control. 

If I am understanding correctly each time there is a milestone release we will pin that so users can update one milestone at a time. effectively having something like current, previous milestone, older milestone. 
Is there any guidance on when to remove the pinned versions?
gitlab releases patches weekly and minor versions monthly (on Wednesdays). https://docs.gitlab.com/policy/maintenance/#versioning How quickly would we be able to update once we go live with the app? what would be needed to match their release cycle. if we pushed and update to this repo every Thursday would that be acceptable?

**Comment by fuzzybair** [comment]
For anyone that wants to use gitlab as a custom app while I am working on this. Here is a working yaml (SSL managed with Nginx Proxy Manager)
```yaml
services:
  gitlab:
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.example.com'
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8888"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['backup_keep_time'] = 2592000
        letsencrypt['enable'] = false
        registry_external_url 'https://git.example.com:5050'
        prometheus_monitoring['enable'] = false
        sidekiq['concurrency'] = 2
    healthcheck:
      test: curl -f http://localhost/-/health
    hostname: git.example.com
    image: gitlab/gitlab-ce:17.11.1-ce.0
    ports:
      - '22:22'
      - '5050:5050'
      - '8888:8888'
    restart: unless-stopped
    volumes:
      - /mnt/pool1/app-data/gitlab/config:/etc/gitlab
      - /mnt/pool1/app-data/gitlab/logs:/var/log/gitlab
      - /mnt/pool1/app-data/gitlab/data:/var/opt/gitlab
```
