### ISSUE TITLE
Immich quicksync transcoding

### ISSUE THREAD

**Issue by backyardaussie** [truenas/apps#2117]
Can we add to the `immich-server` docker extends the options for hwaccel.transcoding.yml ?

I would like to be able to use quicksync in the immich-server for gpu video encoding etc

```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    
```

there is a `immich-machine-learning` `Machine Learning Image Type` question, but nothing for the options for the `immich-server`

thanks
