### ISSUE TITLE
App Request: Versity S3 Gateway

### ISSUE THREAD

**Issue by andrew-d** [truenas/apps#2221]
The [Versity S3 Gateway](https://github.com/versity/versitygw) is a S3-compatible application that's an alternative to MinIO. It has a few advantages over MinIO for homelab use:
1. It stores files as-is on disk, so e.g. a file `my-bucket/path/to/file.txt` is stored on-disk in a file at `/buckets-dir/my-bucket/path/to/file.txt`
2. It's a much simpler project, and is easy to understand and contribute to.
3. It works with an arbitrary POSIX-compatible filesystem so it's easy to point to an existing dataset or directory.

I have this working with a custom app on my local TrueNAS SCALE host; I plan on opening a PR to add this to the app catalog here.

**Comment by andrew-d** [comment]
Here's the `docker-compose.yaml` file that I have running; I'll need to adapt this for the catalog, but I wanted to drop this here in case anyone else needs it before I get to that:
```yaml
name: versitygw
services:
  versitygw:
    build:
      # This is https://github.com/versity/versitygw/releases/tag/v1.0.13
      context: "https://github.com/versity/versitygw.git#63fd82654d9fa618fd11e06011495174534af5cf"
      dockerfile: /mnt/tank/dockerfiles/versitygw.Dockerfile
      args:
        VERSION: "v1.0.13"
        BUILD: "63fd82654d9fa618fd11e06011495174534af5cf"
        TIME: "2025-04-25T20:44:38Z"
        IAM_DIR: &iam_dir "/var/lib/versitygw/iam"

    cap_drop:
      - ALL

    # The command to run; the versitygw binary is the ENTRYPOINT, so we can
    # just specify the args
    command: [
      "--port", ":7070",          # S3 API
      "--admin-port", ":7071",    # admin port, separate for ease of firewalling
      "--health", "/healthz",     # health check on S3 port

      # The IAM directory stores IAM credentials for users
      "--iam-dir", *iam_dir,

      # Run the 'posix' command with a directory to store S3 data there.
      "posix", "/var/lib/versitygw/buckets",

      # "allow symlinked directories at bucket level to be treated as buckets"
      "--bucketlinks",
    ]

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4294967296" # 4GB

    # Load secrets from our environment file
    env_file:
      - /mnt/tank/secrets/versitygw.env

    # Healthcheck the /healthz endpoint
    healthcheck:
      test: [
        "CMD",
        "wget",
        "-T", "10",
        "-q",
        "-O", "-",
        "http://localhost:7070/healthz",
      ]
      interval: 10s
      timeout: 10s
      retries: 12

    ports:
      - "7070:7070"
      - "7071:7071"

    # Restart if it fails, unless stopped
    restart: unless-stopped

    security_opt:
      - no-new-privileges

    # Run as the "apps" user
    user: '568:568'

    volumes:
      - "/mnt/tank/appdata/versitygw:/var/lib/versitygw"
      # TODO: bucket mounts
```
