### ISSUE TITLE
Cloudflared: Allow cloudflared entrypoint without tunnel command to use proxy-dns only

### ISSUE THREAD

**Issue by jmcnatt** [truenas/apps#2241]
I'd like to set up Cloudflared, but without calling the `tunnel` command.  This doesn't currently seem possible within the app.

I'm seeing [here](https://github.com/truenas/apps/blob/master/ix-dev/community/cloudflared/templates/docker-compose.yaml#L21) that the `tunnel` command is being added explicitly and `TUNNEL_TOKEN` is required.

I would like to use this app without `tunnel` and simply call the `cloudflared` entrypoint with the cmd being `proxy-dns --address 0.0.0.0 --port 5053 --upstream https://1.1.1.1/dns-query`.  (these proxy-dns arguments can be added already in the TrueNAS GUI)

I was able to accomplish this with a custom ix app using a series of command arguments, but it would be much easier to use the app provided here to take advantage of updates and not duplicate efforts.

This is a snippet from `/mnt/.ix-apps/user_config.yaml` after the custom app was created.
```yaml
cloudflared:
# ...
  command:
  - proxy-dns
  - --address
  - 0.0.0.0
  - --port
  - '5053'
  - --upstream
  - https://1.1.1.1/dns-query
  - --upstream
  - https://1.0.0.1/dns-query
#  ...
image:
    pull_policy: missing
    repository: cloudflare/cloudflared
    tag: latest
# ...
```
