### ISSUE TITLE
App Request: pterodactyl wings

### ISSUE THREAD

**Issue by jondycz** [truenas/apps#2305]
Since pterodactyl panel has now been added, it would be nice for users to have the ability to also deploy wings.

Wings work in a similar manner to dockage, that it "spawns" new docker containers on the host for each of the game servers thanks to a docker socket passed to the container. (Doesn't do DiD)

The process of linking wings to pterodactyl panel is as follows:
1) user adds a new node in the panel from the web UI and is given a YAML configuration
2) user spins up wings and pastes the YAML content into a config.yml located in /etc/pterodactyl/

I don't think we should require users to extract values from the YAML and paste them one by one into our questions form, so we need a way to easily allow users to change the config. Do we want users to do this through the console via nano or will we allow users to paste the YAML as a multi-line text in the questions?

I'm also not sure how TrueNAS apps work with networks, so I'll probably not be working on implementing this.

Port 8080 is for communication with the panel. Port 2022 is for SFTP and 443 instead of 8080 if ssl enabled (this value can be set in the panel GUI, so can be anything, even self signed certs can be allowed). We could skip supporting SSL right now since we also don't support SSL on the panel. This can also be configured by the user manually or added in the future.

How would pterodactyl wings manage the ports and storage used by spun up game servers? Would this in any way conflict with trueNAS?

Example docker-compose.yaml:
```
services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
      - "443:443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
```

**Comment by stavros-k** [comment]
Any idea why it needs `/var/lib/docker/containers`?
I don't like the idea of giving rw access there (besides that docker in truenas dont use that dir).

---

Assuming those are only configurable via yaml (https://github.com/pterodactyl/wings/blob/35d2e0f0400872ee3edcfc8f675b9581371f3c1c/config/config.go#L127-L143)
It's going to be a mess if we try to map to the default locations and user provides a modified yaml.
In this case yaml will have to be provided via a multiline box, so we can inject values to that yaml before mounting it.
As for networks if that is a requirement for wings, then its going to be postponed until #743

**Comment by jondycz** [comment]
Unfortunately I have no idea how the magic behind wings works. All I know is, that if this is going to be done, it needs to be done right.

If you need any help or explaining on how the panel works, I'm here to answer anything.

**Comment by jondycz** [comment]
For those who want to run this as a "custom yaml app" or in dockge/portainer, you can use this minimal docker-compose. Just replace the CONFIG_PATH and DATA_PATH with your actual mount paths, for example `/mnt/tank/pterodactyl/data` and `/mnt/tank/pterodactyl/config`

```yaml
services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
      - "443:443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 568
      WINGS_GID: 568
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/.ix-apps/docker/containers:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "{CONFIG_PATH}:/etc/pterodactyl/"
      - "{DATA_PATH}:/var/lib/pterodactyl/"
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
```

In your config directory, create a config.yml and paste in the configuration obtained from the Pterodactyl panel (when adding a new node)

**Comment by stavros-k** [comment]
> networks:
>   wings0:
>     name: wings0
>     driver: bridge
>     ipam:
>       config:
>         - subnet: "172.21.0.0/16"
>     driver_opts:
>       com.docker.network.bridge.name: wings0

Does it work without this?

**Comment by jondycz** [comment]
> > networks:
> > wings0:
> > name: wings0
> > driver: bridge
> > ipam:
> > config:
> > - subnet: "172.21.0.0/16"
> > driver_opts:
> > com.docker.network.bridge.name: wings0
> 
> Does it work without this?

I'd like to say yes, but it's still better postponed until networks are fully functional in the UI.

I've tested that it works without tty: true

We'll need to pass through the SSL certs from trueNAS because when panel runs through a proxy with SSL, wings MUST also run with SSL enabled. This is because wings traffic isn't proxied by the panel, rather the browser calls the wings API directly and calling http wings when on an HTTPS site results in mixed content error.

Due to the issue described above I wasn't able to test whether rw access to the docker containers directory is really necessary. Might revisit in the future and test further but currently don't have the luxury of free time.

**Comment by stavros-k** [comment]
If I works without networks we can add it sooner. If this can be tested, even without https, it would be great.

I'm pretty sure it needs rw to docker sock as it spins new containers for each game server.

**Comment by jondycz** [comment]
> If I works without networks we can add it sooner. If this can be tested, even without https, it would be great.
> 
> I'm pretty sure it needs rw to docker sock as it spins new containers for each game server.

I know it does. I was talking about rw access to `/mnt/.ix-apps/docker/containers`

**Comment by jondycz** [comment]
Actually no I take it back. Let's not handle SSL for this app. As cert renewals require restarting the container - it doesn't load the renewed cert automatically. This will become very annoying to the users. It's faster and better to do through a proxy. Just like users would with the panel

**Comment by jondycz** [comment]
So, I was able to get it working without SSL:

My TrueNAS compose file:
```yaml
services:
  wings:
    environment:
      TZ: UTC
      WINGS_GID: 568
      WINGS_UID: 568
      WINGS_USERNAME: pterodactyl
    image: ghcr.io/pterodactyl/wings:v1.6.1
    ports:
      - '4080:4080'
      - '4022:4022'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /mnt/Containers/wings:/etc/pterodactyl/
```

My config.yml for wings (generated in panel):
```yaml
debug: false
uuid: 8ab23545-c026-4f6f-a5d0-1aad5c09a575
token_id: r4hp9bsaC1WyETvK
token: bCnOSSXgk3WgRWqOXf95Yt6ruk31Ud79Z9AQqzpruqs2fadYdcyFWkpH7tDkMgdz
api:
  host: 0.0.0.0
  port: 4080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/192.168.1.10/fullchain.pem
    key: /etc/letsencrypt/live/192.168.1.10/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 4022
allowed_mounts: []
remote: 'http://192.168.1.10:30162'
```

Important things to note: whatever port i specify in the panel (also the port in the yml above) is what the internal wings webserver listens on. (And SFTP too!!!) Even if i enable "wings behind proxy" it binds to the very same port. This is bad because now I cant make wings listen on any custom port and then have my proxy take care of that.

This shouldnt be a problem if we make wings listen on an IP alias.

Currently my setup cant run any game containers due to the following error:
```Error Event [a7acfc8d-0ce4-4464-ba98-58e7524b49a0]: environment/docker: failed to create container: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/pterodactyl/volumes/5c2f815e-6eaa-481e-9514-233a2998307b```

This is probably why it needs access to the docker volumes. It checks for file permissions and overrides them if incorrect.

So in conclusion:
1) tty not necessary
2) binding both docker socket and docker volume paths IS necessary
3) must run as root
4) exposed and listening ports must always match
5) built in ssl is not suitable due to the need to restart the container on certs renewals
6) in order to use ssl with a proxy, the app needs to listen on 443 on a custom IP alias
7) wings by default use DNS resolvers 1.1.1.1 and 1.0.0.1 which are defined in config.yml - this isnt present when copying the generated config from the panel, but the file receives additional entries upon fist startup of wings. This means that local DNS entries DO NOT WORK and the panel needs to be reachable from the external network. - it would be nice if we had this exposed in the TrueNAS UI and a startup script would replace those values in the config.yml file

**Comment by jondycz** [comment]
The full config.yml expanded by the first wings startup:

```yaml
debug: false
app_name: Pterodactyl
uuid: 8ab23545-c026-4f6f-a5d0-1aad5c09a575
token_id: r4hp9bsaC1WyETvK
token: bCnOSSXgk3WgRWqOXf95Yt6ruk31Ud79Z9AQqzpruqs2fadYdcyFWkpH7tDkMgdz
api:
  host: 0.0.0.0
  port: 4080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/192.168.1.10/fullchain.pem
    key: /etc/letsencrypt/live/192.168.1.10/privkey.pem
  disable_remote_download: false
  upload_limit: 100
system:
  root_directory: /var/lib/pterodactyl
  log_directory: /var/log/pterodactyl
  data: /var/lib/pterodactyl/volumes
  archive_directory: /var/lib/pterodactyl/archives
  backup_directory: /var/lib/pterodactyl/backups
  username: pterodactyl
  timezone: UTC
  user:
    uid: 568
    gid: 568
  disk_check_interval: 150
  check_permissions_on_boot: true
  enable_log_rotate: true
  websocket_log_count: 150
  sftp:
    bind_address: 0.0.0.0
    bind_port: 4022
    read_only: false
  crash_detection:
    enabled: true
    detect_clean_exit_as_crash: true
    timeout: 60
  backups:
    write_limit: 0
  transfers:
    download_limit: 0
docker:
  network:
    interface: 172.18.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.18.0.0/16
        gateway: 172.18.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
  container_pid_limit: 512
  installer_limits:
    memory: 1024
    cpu: 100
  overhead:
    override: false
    default_multiplier: 1.05
    multipliers: {}
  use_performant_inspect: true
throttles:
  enabled: true
  lines: 2000
  line_reset_interval: 100
remote: http://192.168.1.10:30162
remote_query:
  timeout: 30
  boot_servers_per_page: 50
allowed_mounts: []
allowed_origins: []
allow_cors_private_network: false
```

**Comment by stavros-k** [comment]
Looks like `/var/lib/docker/containers` is used for reading logs only. https://github.com/pterodactyl/wings/pull/50#discussion_r483364402
Coulnd't find it on the go wings implementation, probably because it users the docker client that masks this, but in their previous I assume js implementation, https://github.com/pterodactyl/daemon/blob/ca642f399528495bfde22760898d6aad297d3e9e/src/controllers/docker.js#L242 it was using it for logs.

I believe we can skip this as the docker client can read logs without this directory.

Your error is probably because you didnt setup a bind mount for `/var/lib/pterodactyl` (which wings is likely able to detect from the docker sock)

Let me know by adding this mount, lets you move further

**Comment by stavros-k** [comment]
> The full config.yml expanded by the first wings startup:

On startup up we would need to "force" the `api.port`, `system.sftp.bind_port`, and probably `system.user.uid/gid` (this might be automatically set from the `WINGS_*ID` var.
Might be wise to also force `system.*_directory` as well, and `system.timezone`

**Comment by jondycz** [comment]
> > The full config.yml expanded by the first wings startup:
> 
> On startup up we would need to "force" the `api.port`, `system.sftp.bind_port`, and probably `system.user.uid/gid` (this might be automatically set from the `WINGS_*ID` var. Might be wise to also force `system.*_directory` as well, and `system.timezone`

Yeah, the UID/GID is set from the env. Implementing this right will be a challenge.

And yes, I didn't bind any storage because I wanted to just make sure it starts and connects to the panel. Didn't even know an app can check whether a path is a docker mount or a generic system path. You're probably right about the error.

**Comment by stavros-k** [comment]
No worries, I'm just assuming all those I mentioned above, based on what I believe it might happening!


> Yeah, the UID/GID is set from the env. Implementing this right will be a challenge.

We can start forcing things that _we know are facts_ and we can force more in the future if needed

**Comment by JamieLee2k** [comment]
I also have the same issue, I have Pterodactyl Panel installed from the App Store, and I have installed Wings from using the custom code that I found here.

> services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
      - "443:443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 568
      WINGS_GID: 568
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/.ix-apps/docker/containers:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "{CONFIG_PATH}:/etc/pterodactyl/"
      - "{DATA_PATH}:/var/lib/pterodactyl/"
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
I changed the Config & Data Path and the port number from 443 to 8443

I also got the config.yml file from Pterodactyl Panel and put it in the folder I created (/mnt/Media Server/wings/config/) and now I got a green heart on Ptero panel and wings now starts without stopping and restarting in a loop, my main issue is I am not able to install any game servers so would this be an issue with the commands I put in or something different?

The error I am getting seems to be common,
> Error Event [f6bce737-d03a-431e-99f5-dff0c46ba38a]: environment/docker: failed to create container: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/pterodactyl/volumes/4b560f73-f084-41d1-8c0b-945a5c6797d8`

I am a novice when it comes to setting this up and I have relied on copy and pasting other peoples commands to get it to work.

**Comment by JamieLee2k** [comment]
I have been doing some investigation and I think my error is the pathing of the custom yaml file, some of the paths in Truenas don't exist, can someone people confirm? and are there any fixes?

**Comment by parkervcp** [comment]
Someone asked me to make a comment about this here... I am no longer on the pterodactyl team but this will be the same for pelican when I start looking at getting it on to truenas as well.

The mounts should be the same in and out of the container as well as in the wings config. When wings sets up the game server container it uses the value in the `config.yml`.

```yml config.yml
system:
  root_directory: /var/lib/pterodactyl # main location for wings data to be stored
  log_directory: /var/log/pterodactyl # where wings writes service and server install logs
  data: /var/lib/pterodactyl/volumes  # where server data is stored
  archive_directory: /var/lib/pterodactyl/archives # pretty sure this is where archives are stored during download and upload
  backup_directory: /var/lib/pterodactyl/backups # where server backups are stored
  tmp_directory: /tmp/pterodactyl # tmp file location used during server installs
```
