### ISSUE TITLE
Home Assistant Stuck in "Deploying" after enabling TLS.

### ISSUE THREAD

**Issue by HugoTea** [truenas/apps#2311]
Home Assistant disables HTTP and switches to only HTTPS when TLS is enabled via the configuration.yml.
This causes the Healthcheck to fail because it only tries to grab http not https.

Personally, I think this is Home Assistant's fault for thinking it's normal or acceptable to have either HTTP or HTTPS and not a redirect like every other web application in the world.

Anyway, people will tell you to resolve this by using a Reverse Proxy instead of enabling TLS directly, but maybe we don't all want to do that.

Instead, I think we should just integrate this possibility into the Health Check and resolve it for good. This is what the Healthcheck currently looks like:
```yml
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: wget --spider --quiet http://127.0.0.1:8123/manifest.json
      timeout: 5s
```

This is a bit of a weird way to do it. Wget will not return 1 on failure, it will return... `4`, which is not allowed https://docs.docker.com/reference/dockerfile/#healthcheck. The only reason this Healthcheck works is because by default wget will retry multiple times on failure. It will retry so many times the Healthcheck's own timeout of 5s will expire and the container will become unhealthy.
On a success wget does return `0`, thankfully.

I've switched mine to this, it returns `0` on first success, or 1 on any failure, instantly. This simplifies the procedure a bit and you can now count on the Healthcheck's own `interval`, `retries` and `timeout` values to be a realistic measure of when a healthcheck will fail.
```yml
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: wget --quiet --tries=1 http://127.0.0.1:8123 --output-document=/dev/null || wget --quiet --tries=1 --no-check-certificate https://127.0.0.1:8123 --output-document=/dev/null || exit 1
      timeout: 5s
```

I also removed `--spider` because I found Home Assistant was rejecting it as `405 Method Not Allowed`, which is exit code `8`, so I don't think it should be relied upon here. Instead we are making a normal GET request and dumping the output into `/dev/null`.

https://github.com/truenas/apps/blob/0b02f1446222b32ebe889de2690a8d859adab8e6/trains/stable/home-assistant/1.4.49/templates/docker-compose.yaml#L44
