### ISSUE TITLE
Expose hostNetwork flag for Immich app

### ISSUE THREAD

**Issue by bvanommen** [truenas/apps#2391]
It would be nice if the hostNetwork flag for the container could be exposed for the immich app. It is generally exposed for most other apps, but not for immich.

I think this could be achieved by adding to `ix-dev/community/immich/questions.yaml`:
```
- variable: host_network
          label: Host Network
          description: |
            Bind to the host network. It's recommended to keep this disabled.
          schema:
            type: boolean
            default: false
```
Though maybe I'm overlooking extra steps, or previous discussion about this.

In my current setup, using adguard running in a docker, my apps fail to make dns requests unless they are bound to the host network. For immich, this means the machine learning container fails to download models.

Thanks a lot!
