### ISSUE TITLE
Syncthing missing timezone configuration

### ISSUE THREAD

**Issue by ZTube** [truenas/apps#2396]
The syncthing application is missing a possibility to define the current timezone.
It defaults to Etc/UTC, no matter the host timezone setting, which might possibly result in sync conflicts.
Therefore I propose the following to be added to syncthings _questions.yaml_:

```yaml
questions:
 - variable: TZ
    group: Syncthing Configuration
    label: Timezone
    schema:
      type: string
      default: Etc/UTC
      required: true
      $ref:
        - definitions/timezone
```
