### ISSUE TITLE
Community Chart Suggestion: matter-server

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/apps#240]
https://github.com/home-assistant-libs/python-matter-server

**Comment by tifredfr** [comment]
Hi,
Matter bridge is an important part of Home Assistant now... This component is starting to become a prerequisite for HA to function properly.

Thx

**Comment by via-justa** [comment]
I'll second @tifredfr. With matter becoming if not already the de-facto standard in the consumer IoT domain, not having it as part of the app creates major issues when using the home assistant app. 

> Or should it be an image that is packed alongside home assistant ? (I mean in the same way that MariaDB is a separated docker container but integrated within the Wordpress app)

There is an "unsupported" [docker image that needs to run as a side container](https://github.com/matter-js/python-matter-server/blob/main/docs/docker.md)

**Comment by JacobDB** [comment]
I'd also like to voice my support for this. When you install Home Assistant as an app within TrueNAS, certain things aren't available, one of which is the self-contained Matter server. I've been trying to migrate from a Home Assistant Green to my NAS, and running in to several issues like this. If you try to initialize Matter, you get prompted to enter a server URL, which is what `python-matter-server` solves (if I understand correctly, it's literally what Home Assistant uses, just separated out).

For what it's worth, I got it to start with the following, but I can't seem to add any devices... will update if I figure that out.

```
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/matter-js/python-matter-server:stable
    ports:
      - 5540:5540/udp
      - 5580:5580/tcp
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - /mnt/HDDs/Applications/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
```

The trick was forwarding the ports manually instead of using "host network" which always failed due "address already in use." I have a feeling host network might be an absolute necessity to get devices to connect, but I'll keep futzing with it...

**Comment by JacobDB** [comment]
Quick update, I got it working, but I imagine this probably isn't ideal as I had to run a few shell commands to enable a "macvlan bridge." I used AI to help (sorry), so I'm sure this is a mess, but here's the config that's currently working for me:

In shell:

```
sudo ip link add macvlan-shim link enp3s0 type macvlan mode bridge
sudo ip addr add 192.168.86.241/32 dev macvlan-shim
sudo ip link set macvlan-shim up
sudo ip route add 192.168.86.240/28 dev macvlan-shim
```

Yaml:

```
networks:
  matter_macvlan:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - gateway: 192.168.86.1
          ip_range: 192.168.86.240/28
          subnet: 192.168.86.0/24
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/matter-js/python-matter-server:stable
    networks:
      - matter_macvlan
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - /mnt/HDDs/Applications/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
```

Then in Home Assistant, I connected to `ws://192.168.86.240:5580/ws` and voila! I'm now able to add devices from Google Home under "multi admin." Not sure about provisioning new devices just yet, don't have a Thread radio for Home Assistant at the moment...

**Comment by JacobDB** [comment]
Managed to try provisioning a wifi device, needed to switch to this to enable IPv6:

```
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/matter-js/python-matter-server:stable
    networks:
      - matter_macvlan
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - /mnt/HDDs/Applications/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro

networks:
  matter_macvlan:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.86.0/24
          gateway: 192.168.86.1
          ip_range: 192.168.86.240/28
        - subnet: fdb7:fb9b:aa9e:166e::/64
          gateway: fdb7:fb9b:aa9e:166e::1
```

Additionally, I confirmed that I'm having to run those shell commands on reboot, but I might just make a startup script...
