### ISSUE TITLE
App Request: Yamtrack

### ISSUE THREAD

**Issue by JacobDB** [truenas/apps#2410]
[Yamtrack](https://github.com/FuzzyGrim/Yamtrack) is a self-hosted media tracker, with support for TV shows, movies, anime, manga, games, books, and comics. It was quite easy to set up as a custom app with the below configuration, but it'd be nice to have it officially in the catalog to simplify updates.

```
services:
  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
  yamtrack:
    container_name: yamtrack
    depends_on:
      - redis
    environment:
      - TZ=America/Chicago
      - SECRET=************************
      - REDIS_URL=redis://redis:6379
      - ADMIN_ENABLED=true
      - URLS=https://track.example.com
    image: ghcr.io/fuzzygrim/yamtrack
    ports:
      - '30174:8000'
    restart: unless-stopped
    volumes:
      - ./db:/yamtrack/db
volumes:
  redis_data: Null
```
