### ISSUE TITLE
Frigate : cache error on restart

### ISSUE THREAD

**Issue by adrian-hoasted** [truenas/apps#2436]
Frigate cache requires a tmpfs and not a bind mount, using a bind mount after a restart will result in a failure to record with the error 
"Error occurred when attempting to maintain recording cache" appearing in the logs

Replacing the cache bind mount with below fixes the error.

```
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

There are many issues on frigate about this, eg: https://github.com/blakeblackshear/frigate/issues/9822

The official documentation for frigate on docker, requires the tmpfs type mount

https://docs.frigate.video/frigate/installation/#docker
