### ISSUE TITLE
Frigate Nvidia hardware acceleration not working with 1.2.0

### ISSUE THREAD

**Issue by Tenster** [truenas/apps#2464]
Hello,

Since the update to version 1.2.0, NVIDIA GPUs no longer function correctly within the container.

The container only starts partially, and even then, it requires manually specifying the following library paths:

/usr/lib/libcuda.so.1  
/usr/lib/libcuda.so  
/usr/lib/libnvcuvid.so  
/usr/lib/libnvcuvid.so.1

Even after this, only the object detection module starts properly. The video encoders still fail to load correctly.

Additionally, nvidia-smi no longer works inside the container—this was functioning in previous versions.

Were there any significant changes in this update besides the IP-related modifications?

**Comment by stavros-k** [comment]
Only ip-related changes happened there.



> Additionally, nvidia-smi no longer works inside the container—this was functioning in previous versions.

This sounds like gpu isn't passed through? Did you check the nvidia gpu in the bottom of the wizard?

**Comment by Tenster** [comment]
Hello,

Thank you for the quick response.

Yes, the GPUs are selected.

Other containers, such as Steam Headless, are working fine with the GPU.

**Comment by stavros-k** [comment]
Check the compose file under `/mnt/.ix-apps/app_configs/frigate/<version>/templates/rendered/docker-compose.yaml` (https://jsonformatter.org/json-to-yaml) If the gpu is added there correctly and image is also correct, then its most likely a frigate issue.

**Comment by Tenster** [comment]
Hi, i cant find an Error i added my config below:

```yaml
  frigate:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - PERFMON
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 128000M
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - GPU-06f5d2e5-59bc-dc30-ac50-10195359c4a2
                - GPU-120340b0-1ea0-2546-e644-071744e926c9
              driver: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: >-
        GPU-06f5d2e5-59bc-dc30-ac50-10195359c4a2,GPU-120340b0-1ea0-2546-e644-071744e926c9
      TRT_MODEL_PREP_DEVICE: '0'
      TZ: Europe/Berlin
      UMASK: '002'
      UMASK_SET: '002'
      YOLO_MODELS: 'yolov7-640,yolov7x-640'
      mem_swappiness: '0'
    group_add:
      - 44
      - 107
      - 568
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: >-
        curl --silent --output /dev/null --show-error --fail
        http://127.0.0.1:5000/api
      timeout: 5s
    image: 'ghcr.io/blakeblackshear/frigate:0.15.1-tensorrt'
    network_mode: host
    platform: linux/amd64
    privileged: false
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    shm_size: 2048M
    stdin_open: false
    tmpfs:
      - '/tmp/cache:size=33554432000'
    tty: false
    user: '0:0'
    volumes:
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: /mnt/ssd/docker-sdd/frigate/config
        target: /config
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: /mnt/main/docker-volumes/frigate/media
        target: /media
        type: bind
      - read_only: false
        target: /tmp
        type: volume
        volume:
          nocopy: false
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: true
        source: /usr/lib/x86_64-linux-gnu/libcuda.so
        target: /usr/lib/libcuda.so
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: true
        source: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        target: /usr/lib/libcuda.so.1
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: true
        source: /usr/lib/x86_64-linux-gnu/libnvcuvid.so
        target: /usr/lib/libnvcuvid.so
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: true
        source: /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
        target: /usr/lib/libnvcuvid.so.1
        type: bind
volumes: {}

```
