### ISSUE TITLE
Community Chart Suggestion: Seafile

### ISSUE THREAD

**Issue by YapWC** [truenas/apps#260]
File sync and share platform like NextCloud, however Seafile is more stable and reliable compared to NextCloud. It is a high performance cloud storage system that has low hardware utilization compared to NextCloud.

Currently there is no alternative to NextCloud for a more simplistic cloud storage system. Having at least one alternative in this case would be ideal.

Here is the seafile docker: [https://github.com/haiwen/seafile-docker](https://github.com/haiwen/seafile-docker)

Is there a way I could directly contribute to accelerate the process of adding this app into TrueNas? Feel free to let me know I would like to contribute!

**Comment by sbcarp** [comment]
+1 for this, NextCloud is painfully slow, and failed to sync my folder with 1 millions files, Seafile is the only solution for me, I had the docker version setup in portainer, which works fine but the set up process wasn't easy, it's good to have in Apps for general users.

**Comment by lmath56** [comment]
This would be a great addition.

**Comment by mreid-tt** [comment]
I also would like a community app for Seafile. In the meantime I have it installed with a YAML config. For those interested this is the template that I used (substitute your values accordingly):
```yaml
services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - "${SEAFILE_MYSQL_VOLUME}:/var/lib/mysql"
    networks:
      - seafile-net
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  memcached:
    image: memcached:1.6.29
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    container_name: seafile
    restart: unless-stopped
    ports:
      - "38180:80"
    volumes:
      - "${SEAFILE_VOLUME}:/shared"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=seafile
      - DB_ROOT_PASSWD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      - DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=ccnet_db
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=seahub_db
      - TIME_ZONE=${TIME_ZONE}
      - INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL}
      - INIT_SEAFILE_ADMIN_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME}
      - SEAFILE_SERVER_PROTOCOL=${SEAFILE_SERVER_PROTOCOL}
      - SITE_ROOT=/
      - NON_ROOT=false
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - SEAFILE_LOG_TO_STDOUT=false
      - ENABLE_SEADOC=${ENABLE_SEADOC}
      - SEADOC_SERVER_URL=${SEAFILE_SERVER_PROTOCOL}://${SEAFILE_SERVER_HOSTNAME}/sdoc-server
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      start_period: 60s
      timeout: 5s
      retries: 10

networks:
  seafile-net:
    name: seafile-net

x-portals:
  - host: 0.0.0.0
    name: Web UI
    path: /
    port: 38180
    scheme: http
```

Note that this version assumes you are placing the Seafile server behind a reverse proxy to publish to the internet (since I didn't want to use their Caddy solution). Also, this does not include the optional SeaDoc server as I didn't need document collaboration.

There were two challenges I had with this:

1. Initially the avatar images were returning 403 errors. The cause was symlinked folders pointing outside the web root. Granting execute permissions to all users on the dataset path leading to the media folder resolved it.
2. If you want to use a non-standard port number you need to place it as part of the `SEAFILE_SERVER_HOSTNAME`. As such, if you had a host as my.domain.com and a port of 1234, your `SEAFILE_SERVER_HOSTNAME` would be `my.domain.com:1234`.
3. If you are using a reverse proxy with a non-standard port you will also need to update the `seahub_settings.py` with a line to recognise the external address like this:
```
CSRF_TRUSTED_ORIGINS = ['https://my.domain.com:1234']
```

Finally, for my implementation I also configured LDAP integration for Seafile, allowing users to authenticate using the LLDAP setup I had previously deployed. This made it easy to manage access by assigning users to groups, and it also unified credentials with other services; so users only need one password across these apps.
