### ISSUE TITLE
App Request: Transmission with OpenVPN

### ISSUE THREAD

**Issue by ping-localhost** [truenas/apps#2632]
- **Name**: OpenVPN and Transmission with WebUI
- **Description**: This container contains OpenVPN and Transmission with a configuration where Transmission is running only when OpenVPN has an active tunnel. It has built-in support for many popular VPN providers to make the setup easier.
- **GitHub**: https://github.com/haugene/docker-transmission-openvpn
- **DockerHub**: https://hub.docker.com/r/haugene/transmission-openvpn/tags

Great add-on for the arr stack as a safer option for the regular Transmission app.

---

This is my current YAML (created via the GUI, made a custom app, cleaned it up and added the health check):

```yaml
services:
  transmission:
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      LOCAL_NETWORK: 192.168.0.0/16
      OPENVPN_PROVIDER: nordvpn
      OPENVPN_USERNAME: USERNAME
      OPENVPN_PASSWORD: PASSWORD
      TRANSMISSION_WEB_UI: flood-for-transmission
      TZ: Europe/Amsterdam
    group_add:
      - 568
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test: wget --quiet --spider http://192.168.0.59:9091/transmission/web/
      timeout: 5s
    hostname: transmission
    image: haugene/transmission-openvpn:latest
    platform: linux/amd64
    ports:
      - mode: ingress
        protocol: tcp
        published: 9091
        target: 9091
    privileged: False
    restart: on-failure
    security_opt:
      - no-new-privileges=true
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/.ix-apps/app_mounts/transmission/transmission_config
        target: /config
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/zstorage/transmission
        target: /data
        type: bind
x-portals:
  - host: 0.0.0.0
    name: Web UI
    path: /
    port: 9091
    scheme: http
```
