### ISSUE TITLE
Community Chart suggestion: motioneye

### ISSUE THREAD

**Issue by ElectronicBattle** [truenas/apps#312]
It's a video camera server: connect your IP / other cameras / CCTV and stream it (LAN or WAN) or record or use it for motion detection.

https://github.com/motioneye-project/motioneye/wiki

The docker compose yaml which I use is very simple (and is easily implemented via dockge for example):

```
version: "3.5"
services:
  motioneye:
    # ToDo: Change from unstable dev/edge to stable GitHub registry release and Docker registry release, once available
    image: ghcr.io/motioneye-project/motioneye:edge
    # https://github.com/motioneye-project/motioneye/pkgs/container/motioneye
    hostname: motioneye
    environment:
      - HOSTNAME=motioneye
    ports:
      # host:container    
      #      - 8081:8081 # if streaming in UI, open this port 
      #        (or choose another in the UI and here)
      - 8765:8765
    volumes:
      # host:container    
      - /etc/localtime:/etc/localtime:ro
      - /dev/dri:/dev/dri
    #  - /mnt/mainraid/docker/data/motioneye/etc:/etc/motioneye
    #  - /mnt/mainraid/docker/data/motioneye/videos:/var/lib/motioneye
    restart: unless-stopped
networks: {}
```
