### ISSUE TITLE
Community Chart Suggestion: uptime kuma DUPLICATE sorry

### ISSUE THREAD

**Issue by ElectronicBattle** [truenas/apps#313]
SORRY - this has already been requested ...will close

The same bloke is behind "dockge": in the case of "Uptime Kuma", please see https://github.com/louislam/uptime-kuma

This is the very straightforward yaml I use in dockge:

```
version: "3.3"
services:
  uptime-kuma:
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
volumes:
  uptime-kuma: {}
networks: {}
```
