### ISSUE TITLE
storj not starting

### ISSUE THREAD

**Issue by Simoneu01** [truenas/apps#393]
Hi!

I've tried multiple times to start the storj app from the catalog but is not working, it's giving a lot of issues.

I've tried to use a simple docker compose with dockge and everything is fine.

```
version: "3.3"
services:
  storagenode:
    image: storjlabs/storagenode:latest
    container_name: storagenode
    volumes:
      - type: bind
        source: /mnt/Apps/storj/
        target: /app/identity
      - type: bind
        source: /mnt/Pool1/storj-data/
        target: /app/config
    ports:
      - 28967:28967/tcp
      - 28967:28967/udp
      - 14002:14002
    restart: unless-stopped
    stop_grace_period: 300s
    environment:
      - WALLET=<Wallet>
      - EMAIL=<email>
      - ADDRESS=<address>
      - STORAGE=1TB
networks: {}

```
