### ISSUE TITLE
Allow Host Networking for Nginx Proxy Manager

### ISSUE THREAD

**Issue by mtwo** [truenas/apps#734]
Now that apps are migrating to Docker (a perfectly smooth experience I might add, great job!), there are some cases where enabling host networking may be advisable. Some TrueNAS apps like Jellyfin already support this, however the Nginx Proxy Manager application lacks this option.

The Docker host networking driver can offer better performance for proxies than the bridge networking driver (referenced in the Docker documentation and [this Stackoverflow benchmark](https://stackoverflow.com/questions/49023800/performance-issues-running-nginx-in-a-docker-container/49274333#49274333)), and it'd be great to give users of the Nginx Proxy Manager app the ability to enable this.

**Comment by stavros-k** [comment]
Sadly NPM, conflicts with webui ports (80,443) with no way to change them (inside the container).
Once we can change those. We can allow host-network

**Comment by mtwo** [comment]
Aha, that makes sense! I’ll raise an issue with NPM.
________________________________

**Comment by stavros-k** [comment]
I'll close this one for now, If that ends up being implemented in NPM, feel free to ping me and I'll re-open!
Thanks!

**Comment by mtwo** [comment]
[do not re-open]

Filed https://github.com/NginxProxyManager/nginx-proxy-manager/issues/4122 on Nginx Proxy Manager

**Comment by razvanphp** [comment]
Can we reopen this?

NPM seems to have been implementing this: https://github.com/snordmann/nginx-proxy-manager/commit/9844df27de4845bdb8589d4c10913566c8f50cce

**Comment by stavros-k** [comment]
Ping me when it's merged and released and I'll reopen

**Comment by mtwo** [comment]
@stavros-k is the new host IP setting for each app compatible with Docker host networking? If so, then we could use that to work around NPM's inability to configure arbitrary ports.

**Comment by stavros-k** [comment]
No, its only when you DONT use host net

**Comment by mtwo** [comment]
@stavros-k one other question: if I were to change the TrueNAS web UI ports, then I could use NPM with host networking, correct? I know that the option isn't available within the UI due to the ports conflicting, but is there any other way to enable host networking?

**Comment by blind-coder** [comment]
> [@stavros-k](https://github.com/stavros-k) one other question: if I were to change the TrueNAS web UI ports, then I could use NPM with host networking, correct? I know that the option isn't available within the UI due to the ports conflicting, but is there any other way to enable host networking?

That would be great. I've been trying to get IPv6 working in NPM for a while before I stumbled over this report.
I have rebound TrueNAS's listeners to different ports specifically so I could get NPM to listen on 80 and 443 and would love to be able to actually use IPv6 in my network.

**Comment by blind-coder** [comment]
I gave up on TrueNAS's integration of NPM and used this docker file instead. Works like a charm after moving TrueNAS's ports to 82 (http) and 444 (https) and then adding Proxy Hosts in NPM for those instead.

Adjust to your hostnames and volume mounts respectively.


```yaml
services:
  app:
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
    image: jc21/nginx-proxy-manager:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/data/npm/data:/data
      - /mnt/data/npm/letsencrypt:/etc/letsencrypt
x-portals:
  - host: truenas.lan
    name: Web UI
    path: /
    port: 81
    scheme: http
```
