### ISSUE TITLE
Paperless-ngx - Add Tika and Gotenberg

### ISSUE THREAD

**Issue by tina-junold** [truenas/apps#837]
Hi,

I would like to see the Paperless-ngx add having additional two containers running, Tika and Gotenberg ([docs](https://docs.paperless-ngx.com/configuration/#optional-services)). 

I'm willing to help with a pull request if necessary. The docker-compose.yml of the paperless-ngx project looks like:

```yaml
    #[...]
    environment:
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg:latest
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
```
