### ISSUE TITLE
Ente app request

### ISSUE THREAD

**Issue by kabatp** [truenas/apps#971]
Ente full back-end and front-end for Ente Auth and Ente Photos with web app and server

https://help.ente.io/self-hosting/

**Comment by d3rm1ch1h0** [comment]
greate, just what i am trying to do with the custom app - without success - yet.

**Comment by shaft8472** [comment]
I've been trying to get this to work on and off... without much luck. I hope someone is reading this and can help us out.

**Comment by ManiacDC** [comment]
Gave Ente a really quick shot, but it's not for me since it doesn't work with existing libraries (without importing them into its system and storing them there), but here's what I did. I ran the quickstart.sh script in another machine, did NOT start ente.

Created the following datasets:
ente
ente/data
ente/postgres-data
ente/minio-data

copied museum.yaml into ente dataset
copied & tweaked the compose.yaml into the custom app, here's what mine looked like:
```yaml
services:
  minio:
    command: server /data --address ":3200" --console-address ":3201"
    environment:
      MINIO_ROOT_PASSWORD: oWjEzsueUE7dADmNsXi9ehyyrIHB
      MINIO_ROOT_USER: minio-user-n5jWwssK
    image: minio/minio
    ports:
      - '3200:3200'
    post_start:
      - command: >
          sh -c '

          #!/bin/sh


          while ! mc alias set h0 http://minio:3200 minio-user-n5jWwssK
          oWjEzsueUE7dADmNsXi9ehyyrIHB 2>/dev/null

          do
            echo "Waiting for minio..."
            sleep 0.5
          done


          cd /data


          mc mb -p b2-eu-cen

          mc mb -p wasabi-eu-central-2-v3

          mc mb -p scw-eu-fr-v3

          '
    volumes:
      - /mnt/Pool1/ApplicationData/ente/minio-data:/data
  museum:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/ente-io/server
    ports:
      - '8080:8080'
    volumes:
      - /mnt/Pool1/ApplicationData/ente/museum.yaml:/museum.yaml:ro
      - /mnt/Pool1/ApplicationData/ente/data:/data:ro
  postgres:
    environment:
      POSTGRES_DB: ente_db
      POSTGRES_PASSWORD: 2gvn11tYBUClVA5g8QZc1C3dWuhs
      POSTGRES_USER: pguser
    healthcheck:
      start_interval: 1s
      start_period: 40s
      test: pg_isready -q -d ente_db -U pguser
    image: postgres:15
    volumes:
      - /mnt/Pool1/ApplicationData/ente/postgres-data:/var/lib/postgresql/data
  socat:
    command: TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200
    depends_on:
      - museum
    image: alpine/socat
    network_mode: service:museum
  web:
    environment:
      ENTE_ALBUMS_ORIGIN: https://monstershare:3002
      ENTE_API_ORIGIN: http://monstershare:8080
    image: ghcr.io/ente-io/web
    ports:
      - '3000:3000'
      - '3002:3002'
```

Note, I ran into an error creating my user. To get around this, I had to set the ENTE_ALBUMS_ORIGIN and ENTE_API_ORIGIN to the correct hostname.

Also, sending an email will be skipped for verification. You can get the 2FA code from the logs of one of the containers. I forget which one now, but I think it was museum.
